### ISSUE TITLE
Running as a Cucumber feature throws an exception

### ISSUE THREAD

**Issue by ankitojha** [cukespace/cukespace#106]
I have configured a framework with cukespace as a runner. However while executing as 'Run as Cucumber Feature', tests are not started it and it throws an exception

```
java.lang.NoClassDefFoundError: javax/enterprise/inject/spi/CDI
	at cucumber.runtime.arquillian.container.CukeSpaceCDIObjectFactory.getInstance(CukeSpaceCDIObjectFactory.java:16)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
```

What could be the possible way to execute scenario as cucumber feature and not as Junit Runner @RunWith(CukeSpace.class)

**Comment by rmannibucau** [comment]
Hi @ankitojha 

you can probably create different dependency sets in 2 executions to make it possible, alternative is to make CukeSpaceCDIObjectFactory defaulting to default factory when CDI is not started/available (but doesnt cover cucumber scope sadly :()

**Comment by ankitojha** [comment]
Can i get anywhere example set for the above alternatives ?

**Comment by rmannibucau** [comment]
Nop, this needs to be done since it is not supported ATM with a flat classpath and single surefire execution.

**Comment by kjayamit** [comment]
I am facing a similar issue. The tests are running fine when using command line or maven tasks. But fails when running a single scenario from IDE.
