### ISSUE TITLE
Cukespace support Managed Mode?

### ISSUE THREAD

**Issue by APIReader** [cukespace/cukespace#48]
Hi,

Not sure this is the right place, but I want to use cukespace in my project and looking at the code two questions spring to mind:

1- Does cukespace support the arquillian Managed Mode (specifically a remote container using an extension of the [JMX protocol](https://github.com/arquillian/arquillian-core/blob/master/protocols/jmx/src/main/java/org/jboss/arquillian/protocol/jmx/AbstractJMXProtocol.java) )?
2- Does cukespace support [multiple deployments] (https://docs.jboss.org/author/display/ARQ/Multiple+Deployments) on the same container ?

Appreciate if anyone can she some light on these questions.

John.

**Comment by rmannibucau** [comment]
Hi

both are supported AFAIK

**Comment by APIReader** [comment]
Hi,

Thanks for the prompt answer. When executing my cucumber tests in managed mode as described above (works fine in embedded mode) I get a request container side to execute a test method called  **performInternalCucumberOperations**. After looking around this method is generated by the [Arquillian Cucumber](https://github.com/cukespace/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/ArquillianCucumber.java#L95) JUnit runner. However since this method doesn't exist in my test class, an error is thrown and the test execution fails. Do you have any idea what is wrong or where to look ? I am using 1.6.0-SNAPSHOT for compatibility reasons.

Thanks,

John.

**Comment by rmannibucau** [comment]
hi

Can you give more details and a stacktrace maybe?

performInternalCucumberOperations shouldnt be an issue with JUnit/surefire/failsafe (that's how we pass our tests BTW).

**Comment by APIReader** [comment]
Hi,

So client side i put a breakpoint [here](https://github.com/arquillian/arquillian-core/blob/master/protocols/jmx/src/main/java/org/jboss/arquillian/protocol/jmx/JMXMethodExecutor.java#L63) where the non existent method performInternalCucumberOperations  is called on my test class T.

The fields of the parameter [InstanceControlledFrameworkMethod ](https://github.com/cukespace/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/ArquillianCucumber.java#L436) are:
 * A for *tes*t
 * *method* has values:
     * T for the *originalClass*
     * *instance* is cucumber.runtime.arquillian.CukeSpace
     * *fMethod* is public void cucumber.runtime.arquillian.ArquillianCucumber.performInternalCucumberOperations(java.lang.Object,org.junit.runner.notification.RunNotifier) throws java.lang.Exception

This causes a call to the [JMX TEST RUNNER](https://github.com/arquillian/arquillian-core/blob/master/protocols/jmx/src/main/java/org/jboss/arquillian/protocol/jmx/JMXTestRunnerMBean.java#L41) to the class name T and method name performInternalCucumberOperations which is invalid and causes the error.

Thanks,

John.

Here is the stack trace for client side up to the method call:

at org.jboss.arquillian.protocol.jmx.JMXMethodExecutor.invoke(JMXMethodExecutor.java:65)
	  at org.jboss.arquillian.container.test.impl.execution.RemoteTestExecuter.execute(RemoteTestExecuter.java:109)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	  at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	  at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:57)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	  at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
	  at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:129)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	  at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:130)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	  at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	  at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:606)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	  at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:136)
	  at org.jboss.arquillian.junit.Arquillian$8.evaluate(Arquillian.java:363)
	  at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:245)
	  at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:422)
	  at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	  at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:259)
	  at org.jboss.arquillian.junit.Arquillian$7.evaluate(Arquillian.java:321)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	  at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:122)
	  at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:71)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:204)
	  at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:422)
	  at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	  at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:218)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:166)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)

**Comment by rmannibucau** [comment]
I see, didnt notice jmx executor was using class/method. This breaks JUnit Description API IMO. Wonder if JMX executor could be enhanced to support class execution and send back results at once.

**Comment by APIReader** [comment]
The [Servlet Protocol](https://github.com/alesj/arquillian/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/v_3/ServletProtocol.java) ,which seems to be working fine judging by your tests, also runs tests based on class/method judging by the   [ServletTestRunner](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java#L106).

**Comment by rmannibucau** [comment]
servlet protocol and local protocol are intensively tested and work.

It is all based on the fact we replace the runner which uses cucumber.runtime.arquillian.ArquillianCucumber.InstanceControlledFrameworkMethod instead of FrameworkMethod. Can be broken if JMX doesn't respect the runner

magic happens in org.jboss.arquillian.junit.container.JUnitTestRunner#execute line 66, you go in org.junit.internal.requests.ClassRequest#ClassRequest(java.lang.Class<?>) which sees the runner (cukespace or arquilliancucumber) then all is in the runner hands which is able to skip not existing methods.

Can you check in your JMX project you pass in those invocations?

**Comment by APIReader** [comment]
The breakpoints are only reached container side, not client side.

when debugging org.jboss.arquillian.junit.container.JUnitTestRunner#execute line 66 runner is of type org.junt.runner.JUnitCore and org.junit.internal.requests.ClassRequest#ClassRequest(java.lang.Class<?>) is passed my test class T .

**Comment by rmannibucau** [comment]
this is fine, ClassRequest will introspect the test class, find @RunWith and instantiate it (ArquillianCucumber). Then that is this runner which will handle the "fake" method.

Do you have a sample on github I can clone to run it locally?

**Comment by APIReader** [comment]
Working on it. I noticed that the [cucumber archive processor](https://github.com/cukespace/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/client/CucumberArchiveProcessor.java#L57) is skipped if it's a JavaArchive. In my case, it is a JavaArchive, could this be the issue ?

Because I use a JavaArchive for deployment, this forced me to add the cukespace dependencies like this:

    String coordinates = "com.github.cukespace:cukespace-core";
        File[] files = Maven.configureResolver().workOffline().loadPomFromFile("pom.xml").resolve(coordinates).withTransitivity().asFile();
        JavaArchive cukeSpaceDeps = ShrinkWrap.create(JavaArchive.class, "cucumber-test");
        for (File file : files) {
            JavaArchive cukeSpaceDep = ShrinkWrap.createFromZipFile(JavaArchive.class, file);
            cukeSpaceDeps = cukeSpaceDeps.merge(cukeSpaceDep);
        }

Could this be the cause ?

**Comment by rmannibucau** [comment]
if the framework can't enrich the application for server side tests with the framework library yes.

**Comment by APIReader** [comment]
I see, is there any way to enrich it using JavaArchives only ? If not, does this mean we can't use cukespace when deploying a JavaArchive ?

**Comment by rmannibucau** [comment]
ATM it is what it means. The only way I know to enrich a jar is to merge the content of the "enrichment" with the application jar but it would more often than it would work so I'm clearly -1 for it.

That said you can always wrap your jar in a war, is it blocking?

**Comment by APIReader** [comment]
I think the correct approach would be to use a WAR even though you could probably make it work using [Auxiliary Archive Appender](https://github.com/arquillian/arquillian-core/blob/master/container/test-spi/src/main/java/org/jboss/arquillian/container/test/spi/client/deployment/AuxiliaryArchiveAppender.java) to add the cucumber dependencies and keep [Cucumber Processor ](https://github.com/cukespace/cukespace/blob/master/core/src/main/java/cucumber/runtime/arquillian/client/CucumberArchiveProcessor.java#L57) to enrich the test jar.

**Comment by rmannibucau** [comment]
Was thinking about it and wondered why it was not the case. The answer IIRC is because it is working with embedded adapters so best thing we can do is surely an info log, not sure it does worth it.

**Comment by APIReader** [comment]
Hi Again :) 

Unfortunately I need my archives to be JavaArchives as well. This seems to be a reasonable scenario to me. 

What would be the steps I need to follow to make cukespace work when deploying JavaArchives?

Thanks again.

**Comment by rmannibucau** [comment]
Well, you'll need to enrich manually your archive with cukespace and its dependencies.

BTW: why do you need to use a jar? Why using a war would be an issue?

**Comment by APIReader** [comment]
I'm working towards using a war. But the issue is I can't get rid of the call testClass.performInternalCucumberOperations which doesn't exist (even when enriching the archive with cucumber dependencies). Is there an easy way to check that the correct runner is used ? 

Stack trace below if you notice anything out of the ordinary:

SEVERE: Failed: murex.connectivity.it.managedinterface.CucumberIntegrationManagedTest.performInternalCucumberOperations
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:673)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:480)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:306)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:241)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:88)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:70)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3178)
	at java.lang.Class.getAnnotations(Class.java:3158)
	at org.junit.runner.Description.createSuiteDescription(Description.java:123)
	at org.junit.internal.runners.ErrorReportingRunner.getDescription(ErrorReportingRunner.java:25)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:159)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.jboss.arquillian.junit.container.JUnitTestRunner.execute(JUnitTestRunner.java:66)
	at org.jboss.arquillian.protocol.jmx.JMXTestRunner.runTestMethodInternal(JMXTestRunner.java:135)
	at org.jboss.arquillian.protocol.jmx.JMXTestRunner.runTestMethod(JMXTestRunner.java:114)
	at murex.connectivity.arquillian.core.protocol.jmx.ManagementExtension$ContextClassLoaderJMXTestRunner.runTestMethod(ManagementExtension.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:75)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:279)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:848)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
	at sun.rmi.transport.Transport$1.run(Transport.java:177)
	at sun.rmi.transport.Transport$1.run(Transport.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by rmannibucau** [comment]
you can debug in the server in JUnitCore or any class you want then load the test class but

    java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

seems to mean you miss classes (kind of ClassNotFoundException) rather than the "fake" method is creating any issue

**Comment by APIReader** [comment]
Hi,

It seems the Junit runner returned by org.junit.runner.Request#getRunner() used in org.junit.internal.requests.FilterRequest#getRunner() server side is of type org.junit.internal.runners.ErrorReportingRunner and not cucumber.runtime.arquillian.ArquillianCucumber as it is in Wildfly+cukespace. This I think is the problem you mentioned earlier. Where is the runner set exaclty ?

**Comment by rmannibucau** [comment]
JUnit does it: https://github.com/junit-team/junit/blob/be4cdb2564e0cf039defb09d983925b7e00e71f0/src/main/java/org/junit/internal/builders/AnnotatedBuilder.java. This builder is triggered from the place I mentionned earlier (in ClassRequest)

**Comment by APIReader** [comment]
Great! Thanks it worked! My tests run fine now. However the runner in my IDE does not show the steps run (only performInternalCucumberOperations is showed). Is this expected ? The generated html report also shows 0 features,steps ran. 

To make sure the tests where run I put a break point and every test methods were executed correctly.

**Comment by rmannibucau** [comment]
1- IDE) it depends the IDE and the cucumber integration but it is possible
2- html) normally it dumps json, is the json empty as well? if so you maybe miss another dependency

**Comment by APIReader** [comment]
I noticed the server writes the JSON report under CucumberConfiguration.reportDirectory and the client reads it from there too. The problem is the server runs in a different root directory than the client hence they are not looking at the same place. I guess this means we have to use absolute paths or have the container/client run at the same root directory?

I also noticed reports are not appended, I guess this means that the same test class running in different containers would not be reported correctly right ?

Regarding the IDE (intellij) problem, could you point me where in the code the client should be retrieving the steps ran server side to be displayed ?

Thanks !

**Comment by rmannibucau** [comment]
- right we use local reporting for now
- right too but you can configure profiles for it (2 configurations)
- about idea: it is this plugin: https://github.com/JetBrains/intellij-plugins/tree/master/cucumber-java. It should surely integrate to arquillian to get the correct reporting when executed server side.

**Comment by APIReader** [comment]
it seems arquillian's [RunAsClient](https://github.com/arquillian/arquillian_deprecated/blob/master/api/src/main/java/org/jboss/arquillian/api/RunAsClient.java) is not support when running with ArquillianCucumber. Is it planned to be in the near future?

**Comment by rmannibucau** [comment]
It is supported (+ you can set your deployment as testable=false since it prevent more than just run as client) but on the class since you don't have test method with cucumber

**Comment by APIReader** [comment]
Sorry I should have specified, the test scenario combines both RunAsClient tests and in container tests (as it is possible in Arquillian). Is this supported ?

**Comment by rmannibucau** [comment]
if you think to warp it is not supported and not intended to be supported short term (but happy to review a pull request if you want to contribute it). Then for other cases limitation comes from the fact cucumber is not executed by step but globally in or out of the container.

**Comment by APIReader** [comment]
Thanks for all the help! Everything works fine. Might add some features as we go along :)

Do you plan on releasing soon ? Previous versions don't work (we depend on arquillian 1.7.Final). We did an internal release of the current snapshot in the meantime..

**Comment by rmannibucau** [comment]
No planned release but can be done next week more or less without blockers - think I'd upgrade to arquillian 1.1.8 before.
