### ISSUE TITLE
trying to upgrade cucumber-reporting

### ISSUE THREAD

**Issue by rmpestano** [cukespace/cukespace#51]
Hi there, i'm trying to update to lastest cucumber report (to verify an issue with jenkins> https://github.com/masterthought/cucumber-reporting/issues/88), here's what i did in pom:

<dependency>
			<groupId>com.github.cukespace</groupId>
			<artifactId>cukespace-core</artifactId>
			<version>1.6.0</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.masterthought</groupId>
					<artifactId>cucumber-reporting</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>0.1.0</version>
			<exclusions>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
				<exclusion>
					<groupId>geronimo-spec</groupId>
					<artifactId>geronimo-spec-jms</artifactId>
				</exclusion>
				<exclusion>
					<groupId>geronimo-spec</groupId>
					<artifactId>geronimo-spec-javamail</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-gpg-plugin</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ant</groupId>
					<artifactId>ant</artifactId>
				</exclusion>
				<exclusion>
					<groupId>antlr</groupId>
					<artifactId>antlr</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.2</version>
			<scope>test</scope>
		</dependency>

I'm running on jboss-managed contaner

and here is the output error:

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.113 sec - in com.procergs.test.acceptance.aluno.AlunoPesquisarAt

Results :

Tests run: 27, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:24.587s
[INFO] Finished at: Thu May 28 17:29:37 BRT 2015
[INFO] Final Memory: 64M/486M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project apm-arq4: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: There was an error in the forked process
[ERROR] java.lang.NoSuchMethodError: net.masterthought.cucumber.ReportBuilder.<init>(Ljava/util/List;Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZZZZLjava/lang/String;Z)V
[ERROR] at cucumber.runtime.arquillian.reporter.CucumberReporter.doReport(CucumberReporter.java:64)
[ERROR] at cucumber.runtime.arquillian.reporter.CucumberReporter.reportOnStop(CucumberReporter.java:33)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)

**Comment by rmannibucau** [comment]
Hi

dont add cucumber-reporting since we depend on <version>0.0.23</version> (could be updated if needed, happy to review a PR if you are motivated).

**Comment by rmpestano** [comment]
Sure, I'll try this weekend and share results
