### ISSUE TITLE
Tests are failling on examples project

### ISSUE THREAD

**Issue by rmpestano** [cukespace/cukespace#72]
Tests in error:
  CukesInBellyFunctionalTest.cucumber.runtime.arquillian.feature.CukesInBellyFunctionalTest » IllegalState

Tests run: 29, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Cukes in Space! Parent ............................. SUCCESS [  3.253 s]
[INFO] Cukes in Space! .................................... SUCCESS [ 17.143 s]
[INFO] Cukes in Space! Examples ........................... FAILURE [10:34 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

stacktrace:

```
java.lang.IllegalStateException: No configurator was found for object of type com.thoughtworks.selenium.DefaultSelenium.
Make sure you have Drone extension depchain for the given browser on the classpath, that is org.jboss.arquillian.extension:arquillian-drone-webdriver-depchain:pom for WebDriver browsers, org.jboss.arquillian.extension:arquillian-drone-selenium-depchain:pom for Selenium 1 browsers and org.jboss.arquillian.graphene:graphene-webdriver:pom for Graphene2 browsers. If you are using different browser extension, please make sure it is on classpath.
Currently registered configurators are: 
	at org.jboss.arquillian.drone.impl.DroneRegistryImpl.getEntryFor(DroneRegistryImpl.java:81)
	at org.jboss.arquillian.drone.impl.DroneConfigurator.getDroneConfigurator(DroneConfigurator.java:127)
	at org.jboss.arquillian.drone.impl.DroneConfigurator.prepare(DroneConfigurator.java:86)
	at org.jboss.arquillian.drone.impl.DroneConfigurator.prepareDrone(DroneConfigurator.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.drone.impl.DroneLifecycleManager.beforeClass(DroneLifecycleManager.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:87)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:201)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:426)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:218)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:166)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

are you experiencing same behaviour? I'm on windows box here

**Comment by rmannibucau** [comment]
Did you setup chrome webdriver? I put it in my settings.xml cause path is rarely portable

**Comment by rmpestano** [comment]
Hi,

did not configured chrome webdrive but also its failing on firefox, I'm facing this issue: http://stackoverflow.com/questions/13514338/failed-to-connect-to-binary-firefoxbinary-with-selenium-in-maven

here is test output when using firefox as webdriver:

```
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'pestano', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-42-generic', java.version: '1.8.0_72'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:142)
	... 11 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:
�бунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1472920890741	DeferredSave.extensions.json	DEBUG	Save changes
1472920890741	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1472920890741	addons.xpi-utils	DEBUG	Updating add-on states
1472920890742	addons.xpi-utils	DEBUG	Writing add-ons list
1472920890743	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1472920890743	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1472920890744	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/loop@mozilla.org.xpi
1472920890745	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1472920890763	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1472920890763	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1472920890763	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-pt-BR@firefox.mozilla.org.xpi
1472920890765	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-pt-PT@firefox.mozilla.org.xpi
1472920890767	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1472920890768	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1472920890771	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1472920890772	addons.manager	DEBUG	Provider finished startup: XPIProvider
1472920890772	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1472920890772	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1472920890772	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1472920890773	addons.manager	DEBUG	Starting provider: GMPProvider
1472920890778	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1472920890779	addons.manager	DEBUG	Provider finished startup: GMPProvider
1472920890779	addons.manager	DEBUG	Starting provider: PluginProvider
1472920890779	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1472920890779	addons.manager	DEBUG	Provider finished startup: PluginProvider
1472920890780	addons.manager	DEBUG	Completed startup sequence
1472920892080	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1472920892080	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1472920892080	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1472920892179	DeferredSave.extensions.json	DEBUG	Write succeeded
1472920892179	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1472920892179	DeferredSave.extensions.json	DEBUG	Starting timer
1472920892191	addons.repository	DEBUG	No addons.json found.
1472920892191	DeferredSave.addons.json	DEBUG	Save changes
1472920892194	DeferredSave.addons.json	DEBUG	Starting timer
1472920894105	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1472920894105	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1472920894106	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1472920894112	DeferredSave.extensions.json	DEBUG	Starting write
1472920894113	DeferredSave.addons.json	DEBUG	Starting write
1472920894129	DeferredSave.extensions.json	DEBUG	Write succeeded
1472920894131	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 21 more

set 03, 2016 1:42:14 PM org.apache.openejb.client.EventLogger log
```

**Comment by rmannibucau** [comment]
Since v2 is out +1 - was not the case when the setup was done.

**Comment by rmpestano** [comment]
+1 for travis also?

**Comment by rmannibucau** [comment]
Yep (not the same pr if possible ;))
Also happy with a win build if you think it does worth it
