### ISSUE TITLE
Features file option always returns null pointer exception

### ISSUE THREAD

**Issue by RajAsapu** [cukespace/cukespace#90]
I have my project in the below structure
project
   | 
      module
                  |
                    src
                         |
                          test
                               |
                               java
                                     |
                                      RunTest
                               resources
                                     |
                                     features
                                           |
                                            pageobjects
                                                           |
                                                            PageIndexCreatePage.feature

and RunTest file has the below code

```
import cucumber.api.CucumberOptions;
import cucumber.api.java.Before;
import cucumber.runtime.arquillian.CukeSpace;
import org.arquillian.cube.*;
import org.junit.runner.RunWith;

@RunWith(CukeSpace.class)
@CucumberOptions(features={"classpath:pageobjects/Page_Index_CreatePage.feature"},glue = {"classpath:stepdef", "classpath:setup"},plugin = {"pretty", "html:target/integration-cucumber", "json:target/integration-cucumber.json"},tags = {"~@Intg"})
public class RunTest {
   // Code }
```

This is always returning Null Pointer Exception, I am not sure why . If it couldnt find the feature file path , it can print the path and throw an exception which will make sense. Below is the stack trace

`java.lang.NullPointerException
	at cucumber.runtime.arquillian.feature.Features.featurePath(Features.java:39)
	at cucumber.runtime.arquillian.feature.Features.findFeatures(Features.java:203)
	at cucumber.runtime.arquillian.feature.Features.createFeatureMap(Features.java:69)
	at cucumber.runtime.arquillian.ArquillianCucumber.performInternalCucumberOperations(ArquillianCucumber.java:134)
	at cucumber.runtime.arquillian.ArquillianCucumber$InstanceControlledFrameworkMethod.invokeExplosively(ArquillianCucumber.java:449)
	at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
	at org.jboss.arquillian.junit.standalone.LocalTestMethodExecutor.execute(LocalTestMethodExecutor.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:136)
	at org.jboss.arquillian.junit.Arquillian$8.evaluate(Arquillian.java:372)
	at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:246)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:431)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:55)
	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:260)
	at org.jboss.arquillian.junit.Arquillian$7$1.invoke(Arquillian.java:324)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.execute(ClientBeforeAfterLifecycleEventExecuter.java:99)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.on(ClientBeforeAfterLifecycleEventExecuter.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.fireCustomLifecycle(EventTestRunnerAdaptor.java:159)
	at org.jboss.arquillian.junit.Arquillian$7.evaluate(Arquillian.java:317)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:122)
	at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:71)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:205)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:431)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:55)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:219)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:167)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

Note : The same feature options are working when i run with Cucumber.class

**Comment by FibreFoX** [comment]
Have you tried `classpath:features/pageobjects/Page_Index_CreatePage.feature` ?

**Comment by RajAsapu** [comment]
Yeah i tried with all those combinations like
classpath:features/pageobjects/Page_Index_CreatePage.feature
classpath:Page_Index_CreatePage.feature

**Comment by rmannibucau** [comment]
I think it should be

> classpath:features/pageobjects/PageIndexCreatePage.feature

since you don't follow the convention which is PageIndexCreatePage.java -> page_index_create_page.feature (same package)

**Comment by RajAsapu** [comment]
No its the right file name , i misspelled it. Modified the description.

**Comment by FibreFoX** [comment]
Have you checked if `@RunAsClient` helps? As far as I understood this changes the location of the executed class to your local machine.

Instead "classpath", I have a working example like this:
```java
@RunWith(ArquillianCucumber.class)
@RunAsClient
@CucumberOptions(
        glue = "de.dynamicfiles.projects.testproject.cucumberglue",
        features = "src/test/resources/cucumber/visitWebsite.feature",
        plugin = {"html:target/cucumber"}
)
public class SimpleCucumberWebsiteTest {

}

```

**Comment by RajAsapu** [comment]
@rmannibucau : Does null pointer exceptions means that it couldn't find the feature file ? and it is erroring in the below code

`  public static String featurePath(final Class<?> javaClass) {
        return javaClass.getPackage().getName().replace('.', '/')
                + '/' + createClassNameSubPackage(javaClass.getSimpleName()) + EXTENSION;
    }`
@FibreFoX : I will try it now

**Comment by rmannibucau** [comment]
I'm tempted to say it is more due to the fact you didnt put your class in a package so javaClass.getpackage is null (not supported case ATM but feel free to PR it), something like

> (javaClass.getPackage() == null ? "" : (javaClass.getPackage().getName().replace('.', '/') + '/'))

**Comment by RajAsapu** [comment]
@rmannibucau : Could you please explain , i am having my files in the pageobjects folder which is below the features folder . Are you saying that it couldnt consider these as packages ?

**Comment by rmannibucau** [comment]
RunTest is not in a package, concretely create a "test" folder, add RunTest inside and add at the top ̀package test;`

**Comment by RajAsapu** [comment]
Yeah that works , i will create a pull requesting addressing this issue

**Comment by Susirya** [comment]
@rmannibucau : Hello! Please correct me if i'm wrong, but i think i have similar trouble. 
I'm getting:
```
Got no path to feature directory or feature file
0 Scenarios
0 Steps
0m0.000s
``` 
while setting `featureHome` path using only `arquillian.xml` (NOT using `@CucumberOptions` in RunnerTest class). RunnerTest looks like:
```
package cucumbertestrunner;
import cucumber.runtime.arquillian.CukeSpace;
import org.junit.runner.RunWith;
@RunWith(CukeSpace.class)
public class RunnerTest {}
```
And `arquillian.xml` content:
```
  <extension qualifier="cucumber">
    <property name="report">true</property>
    <property name="report-directory">target/cucumber-report</property>
    <property name="options">--glue stepdefs</property>
    <property name="featureHome">src/test/resources/features</property>
  </extension>

  <extension qualifier="webdriver">
    <property name="browser">${browser}</property>
    <property name="browserCapabilities">${browserCapabilities}</property>
  </extension>
```
Project structure looks like this:
```
project
    | module
        | src
            | test
                | java
                    | cucumbertestrunner
                        RunTest.java
                    | stepdefs
                        | ..... (sub packs with stepdefs) 
                    |resources
                        |  features
                            | ..... (sub dirs with .feature)
                            SomeFeaturefile.feature
                            SomeFeaturefile.feature 
                            ...
```
(Yes, i'm not following naming convention, but it's a requirement "from above")
I looked through code in `BaseCukeSpace#performInternalCucumberOperations:100-101` and it seems like the last time when `CucumberSearcher ` tries to lookup a .feature file in separate path is in `Features#createFeatureMap:122` 
```
120            findWithCucumberSearcher(loader, path, list);
121            if (home != null) {
122                findWithCucumberSearcher(loader, home + path, list);
123            }
```
Is it possible that in `line 122` adding `path` is redundant (to resolve "only in directory" lookup)? 
Or maybe it's worth to add another 
```
12x                findWithCucumberSearcher(loader, home, list) 
```
for such cases where .feature files are placed "unconventionally"?

**Comment by rmannibucau** [comment]
@Susirya featureHome is to not repeat a base folder but algorithm resolution doesnt scan for features until you use the corresponding syntax

**Comment by Susirya** [comment]
@rmannibucau sorry, but what "corresponding syntax" are you taking about? Is it different from standard cucumber-jvm behaviour and where can i read about it? Thanks in advance!

**Comment by rmannibucau** [comment]
@Susirya it should be the same than cucumber-jvm

**Comment by Susirya** [comment]
@rmannibucau may i ask you to suggest any way to resolve the problem with scanning of .feature files with such project structure? Or should i create separate issue to discuss it?

**Comment by rmannibucau** [comment]
@Susirya featureHome is just a prefix, it doesnt imply any scanning by itself, did you try to specify the folder explicitly on the class?

**Comment by Susirya** [comment]
@rmannibucau Yup, it works as suppose to. But i need to set it in runtime and can't do this with annotations...

**Comment by rmannibucau** [comment]
@Susirya not sure what this means to be honest, you can switch feature files with maven profiles and correct resource configuration. Probably easier: write one test class per profile and put the annotation there

**Comment by Susirya** [comment]
@rmannibucau Oh... You are right. I haven't thought about such workaround. Thanks a lot for another point of view!
